# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Setup BATS unit test framework
    - name: Setup BATS
      uses: mig4/setup-bats@master
      with:
        bats-version: 1.1.0

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out codes
      uses: actions/checkout@v2

    # Run the unit tests by Bats
    - name: Test
      run: bats -r tests
